---
dependencies:
  - { role: commons/os-checker }
  - { role: commons/pre-install, pkgs: [ "kubectl={{ kube_version }}-00", "kubelet={{ kube_version }}-00", "kubernetes-cni", "kubeadm" ], locked_pkgs: [ "kubectl", "kubelet", "kubernets-cni", "kubeadm"] }
